//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equalsys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Karyawan
    {
        public long Id { get; set; }
        public string NamaDepan { get; set; }
        public string NamaTengah { get; set; }
        public string NamaBelakang { get; set; }
        public System.DateTime TanggalLahir { get; set; }
        public string JenisKelamin { get; set; }
        public string Alamat { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Pekerjaan { get; set; }
    }
}
