//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equalsys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pekerjaan
    {
        public long Id { get; set; }
        public string NamaPekerjaan { get; set; }
        public System.DateTime TanggalMulai { get; set; }
        public System.DateTime TanggalBerakhir { get; set; }
        public decimal Gaji { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
